from __future__ import annotations

from coord_harness.core.enums import RegimeLabel
from coord_harness.logging.schema import (
    BenchmarkSection,
    BudgetSection,
    DerivedSection,
    ModelSection,
    OutcomeSection,
    ProvenanceSection,
    RunSection,
    TopologySection,
    TrialSummary,
)


def test_trial_summary_roundtrip() -> None:
    summary = TrialSummary(
        run=RunSection(
            experiment_id="exp",
            trial_id="trial",
            framework_id="coord_harness_v1",
            stage="clean",
            mode="research_strict",
            baseline="ma_ft",
            seed=7,
            status="completed",
            started_at="2026-01-01T00:00:00Z",
            completed_at="2026-01-01T00:00:01Z",
            config_digest="abc",
            decision_prompt_template_version="decision-v2",
            message_serializer_version="message-v2",
        ),
        model=ModelSection(
            alias="mock-mini",
            panel_tier="sweep",
            provider="mock",
            model_id="mock/p0a-deterministic-v1",
            requested_model_id="mock/p0a-deterministic-v1",
            allow_auto_routing=False,
            routing={},
            temperature=0.0,
            top_p=1.0,
            max_completion_tokens=64,
            strict_routing_required=True,
            runtime_metadata={},
            route_metadata_examples=[],
        ),
        benchmark=BenchmarkSection(
            family="craft_mini",
            stage="clean",
            split="smoke",
            dataset_revision="local-mini-v2",
            task_schema_version="mcq-partial-info-v1",
            dataset_digest="digest",
            dataset_path="data/tasks.jsonl",
            manifest_path="data/manifest.yaml",
            source_kind="repo_local_pack",
            stubbed=True,
            task_count=1,
            task_ids=["t1"],
            scoring="exact_match_binary",
        ),
        topology=TopologySection(
            preset="star",
            agent_count=5,
            root_agent="agent_0",
            edge_count=8,
            max_in_degree=4,
            max_out_degree=4,
            edges=[("agent_0", "agent_1")],
        ),
        budget=BudgetSection(
            total_billed_token_budget_per_task=100,
            message_token_budget=32,
            task_prompt_tokens=[10],
            task_completion_tokens=[8],
            task_billed_tokens=[18],
            task_inter_agent_tokens=[6],
            task_model_call_counts=[2],
            mean_billed_tokens=18.0,
            max_billed_tokens=18,
            mean_inter_agent_tokens=6.0,
            max_inter_agent_tokens=6,
        ),
        outcomes=OutcomeSection(
            task_count=1,
            accuracy=1.0,
            score_mean=1.0,
            score_std=0.0,
            score_sum=1.0,
            lift_vs_sa_star=0.1,
            regime=RegimeLabel.HELP,
            attacked_tasks=0,
            attack_success_rate=None,
            infection_spread_rate=None,
        ),
        derived=DerivedSection(F=1.0, rho=0.0, B=1.0, C=0.5, B_source="x", total_messages=2, mean_message_tokens=10.0),
        provenance=ProvenanceSection(
            config_path="cfg",
            output_dir="out",
            python_version="3.12",
            platform="test",
            decision_prompt_hash="hash1",
            message_serializer_hash="hash2",
            model_catalog_snapshot_hash=None,
            model_catalog_snapshot_fetched_at=None,
        ),
        events_path="out/events.jsonl",
    )
    restored = TrialSummary.model_validate_json(summary.model_dump_json())
    assert restored.outcomes.regime is RegimeLabel.HELP
